<?php

/**
 * BaseDocumentoDeFacturacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $doc_id
 * @property string $doc_codigo
 * @property timestamp $doc_fecha_emision
 * @property integer $doc_cliente_id
 * @property integer $doc_proveedor_id
 * @property string $doc_responsable
 * @property decimal $doc_sub_total
 * @property decimal $doc_total_documento
 * @property decimal $doc_iva
 * @property integer $doc_tipo
 * @property Cliente $Cliente
 * @property Proveedor $Proveedor
 * @property Doctrine_Collection $DetalleDocumento
 * 
 * @method integer                getDocId()               Returns the current record's "doc_id" value
 * @method string                 getDocCodigo()           Returns the current record's "doc_codigo" value
 * @method timestamp              getDocFechaEmision()     Returns the current record's "doc_fecha_emision" value
 * @method integer                getDocClienteId()        Returns the current record's "doc_cliente_id" value
 * @method integer                getDocProveedorId()      Returns the current record's "doc_proveedor_id" value
 * @method string                 getDocResponsable()      Returns the current record's "doc_responsable" value
 * @method decimal                getDocSubTotal()         Returns the current record's "doc_sub_total" value
 * @method decimal                getDocTotalDocumento()   Returns the current record's "doc_total_documento" value
 * @method decimal                getDocIva()              Returns the current record's "doc_iva" value
 * @method integer                getDocTipo()             Returns the current record's "doc_tipo" value
 * @method Cliente                getCliente()             Returns the current record's "Cliente" value
 * @method Proveedor              getProveedor()           Returns the current record's "Proveedor" value
 * @method Doctrine_Collection    getDetalleDocumento()    Returns the current record's "DetalleDocumento" collection
 * @method DocumentoDeFacturacion setDocId()               Sets the current record's "doc_id" value
 * @method DocumentoDeFacturacion setDocCodigo()           Sets the current record's "doc_codigo" value
 * @method DocumentoDeFacturacion setDocFechaEmision()     Sets the current record's "doc_fecha_emision" value
 * @method DocumentoDeFacturacion setDocClienteId()        Sets the current record's "doc_cliente_id" value
 * @method DocumentoDeFacturacion setDocProveedorId()      Sets the current record's "doc_proveedor_id" value
 * @method DocumentoDeFacturacion setDocResponsable()      Sets the current record's "doc_responsable" value
 * @method DocumentoDeFacturacion setDocSubTotal()         Sets the current record's "doc_sub_total" value
 * @method DocumentoDeFacturacion setDocTotalDocumento()   Sets the current record's "doc_total_documento" value
 * @method DocumentoDeFacturacion setDocIva()              Sets the current record's "doc_iva" value
 * @method DocumentoDeFacturacion setDocTipo()             Sets the current record's "doc_tipo" value
 * @method DocumentoDeFacturacion setCliente()             Sets the current record's "Cliente" value
 * @method DocumentoDeFacturacion setProveedor()           Sets the current record's "Proveedor" value
 * @method DocumentoDeFacturacion setDetalleDocumento()    Sets the current record's "DetalleDocumento" collection
 * 
 * @package    SICAR
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentoDeFacturacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documento_de_facturacion');
        $this->hasColumn('doc_id', 'integer', 6, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             'length' => 6,
             ));
        $this->hasColumn('doc_codigo', 'string', 10, array(
             'type' => 'string',
             'unique' => true,
             'length' => 10,
             ));
        $this->hasColumn('doc_fecha_emision', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('doc_cliente_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('doc_proveedor_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('doc_responsable', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('doc_sub_total', 'decimal', 6, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 6,
             ));
        $this->hasColumn('doc_total_documento', 'decimal', 6, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 6,
             ));
        $this->hasColumn('doc_iva', 'decimal', 6, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 6,
             ));
        $this->hasColumn('doc_tipo', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'doc_cliente_id',
             'foreign' => 'cli_id'));

        $this->hasOne('Proveedor', array(
             'local' => 'doc_proveedor_id',
             'foreign' => 'prv_id'));

        $this->hasMany('DetalleDocumentoDeFacturacion as DetalleDocumento', array(
             'local' => 'doc_id',
             'foreign' => 'det_documento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}