<?php

/**
 * BaseDetalleDocumentoDeFacturacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $det_id
 * @property string $det_codigo
 * @property integer $det_cantidad
 * @property string $det_descripcion
 * @property decimal $det_valor_unitario
 * @property decimal $det_valor_total
 * @property integer $det_documento_id
 * @property integer $det_producto_id
 * @property DocumentoDeFacturacion $DocumentoDeFacturacion
 * @property Producto $Producto
 * 
 * @method integer                       getDetId()                  Returns the current record's "det_id" value
 * @method string                        getDetCodigo()              Returns the current record's "det_codigo" value
 * @method integer                       getDetCantidad()            Returns the current record's "det_cantidad" value
 * @method string                        getDetDescripcion()         Returns the current record's "det_descripcion" value
 * @method decimal                       getDetValorUnitario()       Returns the current record's "det_valor_unitario" value
 * @method decimal                       getDetValorTotal()          Returns the current record's "det_valor_total" value
 * @method integer                       getDetDocumentoId()         Returns the current record's "det_documento_id" value
 * @method integer                       getDetProductoId()          Returns the current record's "det_producto_id" value
 * @method DocumentoDeFacturacion        getDocumentoDeFacturacion() Returns the current record's "DocumentoDeFacturacion" value
 * @method Producto                      getProducto()               Returns the current record's "Producto" value
 * @method DetalleDocumentoDeFacturacion setDetId()                  Sets the current record's "det_id" value
 * @method DetalleDocumentoDeFacturacion setDetCodigo()              Sets the current record's "det_codigo" value
 * @method DetalleDocumentoDeFacturacion setDetCantidad()            Sets the current record's "det_cantidad" value
 * @method DetalleDocumentoDeFacturacion setDetDescripcion()         Sets the current record's "det_descripcion" value
 * @method DetalleDocumentoDeFacturacion setDetValorUnitario()       Sets the current record's "det_valor_unitario" value
 * @method DetalleDocumentoDeFacturacion setDetValorTotal()          Sets the current record's "det_valor_total" value
 * @method DetalleDocumentoDeFacturacion setDetDocumentoId()         Sets the current record's "det_documento_id" value
 * @method DetalleDocumentoDeFacturacion setDetProductoId()          Sets the current record's "det_producto_id" value
 * @method DetalleDocumentoDeFacturacion setDocumentoDeFacturacion() Sets the current record's "DocumentoDeFacturacion" value
 * @method DetalleDocumentoDeFacturacion setProducto()               Sets the current record's "Producto" value
 * 
 * @package    SICAR
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleDocumentoDeFacturacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_documento_de_facturacion');
        $this->hasColumn('det_id', 'integer', 6, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             'length' => 6,
             ));
        $this->hasColumn('det_codigo', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('det_cantidad', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('det_descripcion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('det_valor_unitario', 'decimal', 6, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 6,
             ));
        $this->hasColumn('det_valor_total', 'decimal', 6, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 6,
             ));
        $this->hasColumn('det_documento_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('det_producto_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DocumentoDeFacturacion', array(
             'local' => 'det_documento_id',
             'foreign' => 'doc_id'));

        $this->hasOne('Producto', array(
             'local' => 'det_producto_id',
             'foreign' => 'pro_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}