<?php

/**
 * DetalleDocumentoDeFacturacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleDocumentoDeFacturacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleDocumentoDeFacturacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleDocumentoDeFacturacion');
    }
}