<?php

/**
 * DocumentoDeFacturacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentoDeFacturacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentoDeFacturacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentoDeFacturacion');
    }
}